title: nicTheDevs musings
author: nic-ball
email: nicthedev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
A place for testing new ideas and writing about the constant journey to be a better software developer.

theme: minima

# social links
twitter_username: codeOfNunchuck # DO NOT include the @ character, or else the build will fail!
github_username:  nic-ball # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
